version: '3'

services:
  backend:
    container_name: backend-desafio
    build:
      context: ./backend
    ports:
      - 3001:3001
    networks:
      - red

  frontend:
    container_name: front-desafio
    build:
      context: ./frontend
    ports:
      - 8080:8080
    networks:
      - red

networks:
  red:
    driver: bridge 