name: Java CI with Maven

on:
  push:
    branches: [ "rama_pipeline" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Clean
      working-directory: backend/apicar
      run: mvn clean
    - name: Build
      working-directory: backend/apicar
      run: mvn -B package

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Clean
      working-directory: backend/apicar
      run: mvn clean
    - name: Build
      working-directory: backend/apicar
      run: mvn -B package
    - name: Test
      working-directory: backend/apicar
      run: mvn test
